import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

import { LoadingLayout } from "@/components";

import "@/scss/globals.scss";

const vazir = Vazirmatn({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("layout================> page");

  return (
    <html lang="fa">
      <body
        className={vazir.className}
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          padding: 0,
          margin: 0,
        }}
      >
        <LoadingLayout>
          <div>{children}</div>
        </LoadingLayout>
      </body>
    </html>
  );
}
